imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                port: %database_port%
                user: %database_user%
                password: %database_password%
                dbname: %database_name%
                charset: UTF8
    orm:
        default_entity_manager:   default
        entity_managers:
            default:
                connection:       default
                mappings:
                    eZSyliusBundle: ~


framework:
    esi:             ~
    translator:      { fallback: "%locale_fallback%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
        # Note: changing this will break legacy extensions that rely on the default name to alter AJAX requests
        # See https://jira.ez.no/browse/EZP-20783
        field_name: ezxform_token
    validation:      { enable_annotations: true }
    # Place "eztpl" engine first intentionnally.
    # This is to avoid template name parsing with Twig engine, refusing specific characters
    # which are valid with legacy tpl files.
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale_fallback%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        # Note: eZ Publish also allows session name and session cookie configuration to be per SiteAccess, by
        #       default session name will be set to "eZSESSID{siteaccess_hash}" (unique session name per siteaccess)
        #       Further reading on sessions: https://doc.ez.no/display/EZP/Session
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ eZDemoBundle,eZSyliusBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sylius_cart:
    resolver: ezsylius.cart_item_resolver
    classes:
        cart:
            controller: Crevillo\EzSyliusBundle\Controller\CartController

sylius_order:
    driver: doctrine/orm
    classes:
        order_item:
            model: Crevillo\EzSyliusBundle\Entity\CartItem

sylius_money: ~

sylius_translation:
    default_locale: %locale_fallback%
    locale_provider: sylius.translation.locale_provider.contextual


